spring:
  application:
    name: service-jrewarded-management
  datasource:
    url: jdbc:postgresql://postgresql:5432/dev-scr #TODO: change
    username: scr
    password: chicoziggy #TODO: secret
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka.kafka.svc.cluster.local:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: http://schema-registry.kafka.svc.cluster.local:8081 #TODO: change
      specific.avro.reader: true
      security.protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        username: user1
        password: RWqadPW9cb #TODO: secret
messaging:
  topics:
    rewarded-creation-notification: srm-rewarded-entity-creation-events
  group-id: my_group
